name: my_art
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  line_awesome_flutter: ^2.0.0
  intl: ^0.19.0

  # -- Fonts
  google_fonts: ^6.1.0

  # -- State Management
  get: ^4.6.6

  #  Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

  custom_clippers: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/welcome_images/
    - assets/images/forget_password/
    - assets/images/profile_picture/
    - assets/logo/
    - assets/dashboard/images/icon-aid-kit.png
    - assets/dashboard/images/vector.png
    - assets/dashboard/images/group-1.png
    - assets/dashboard/images/icon-user.png
    - assets/dashboard/images/group-3.png
    - assets/dashboard/images/group-10.png
    - assets/dashboard/images/icon-calendar.png
    - assets/dashboard/images/icon-newspaper.png
    - assets/dashboard/images/group-2.png
    - assets/dashboard/images/icon-user-plus.png